name: Build & deploy Docker image
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Publish docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mrmlik12/dcr:latest
