name: Build & deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore src/Dcr.sln
      - name: Build project
        run: dotnet build src/Dcr.sln --configuration Release
      - name: Test project
        run: dotnet test src/Dcr.sln
      - name: Clean Project
        run: dotnet clean src/Dcr.sln
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          usedocker: true
          procfile: "worker: dotnet Dcr.dll"
